/* SPDX-License-Identifier: GPL-2.0-only */

#include <commonlib/helpers.h>
#include <soc/gpio.h>
#include <intelblocks/gpio_defs.h>

#include "../../gpio.h"

/* Less verbose GPIO macros, names have the same length on purpose */
#define PAD_CFG_IN_DRV(pad)		PAD_CFG_GPI_INT(pad, NONE, DEEP, OFF)
#define PAD_CFG_OUTPUT(pad, lvl)	PAD_CFG_GPO(pad, lvl, DEEP)
#define PAD_CFG_NATIVE(pad, fun)	PAD_CFG_NF(pad, NONE, DEEP, fun)

/* Pad configuration in ramstage */
static const struct pad_config gpio_table[] = {
	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group A ------- */
	PAD_CFG_NATIVE(GPP_A0, NF3),
	PAD_CFG_NATIVE(GPP_A1, NF3),
	PAD_CFG_NATIVE(GPP_A2, NF3),
	PAD_CFG_NATIVE(GPP_A3, NF3),
	PAD_CFG_NATIVE(GPP_A4, NF3),
	PAD_CFG_NATIVE(GPP_A5, NF3),
	PAD_CFG_IN_DRV(GPP_A6),
	PAD_CFG_NATIVE(GPP_A7, NF3),
	PAD_CFG_NATIVE(GPP_A8, NF1),
	PAD_CFG_NATIVE(GPP_A9, NF3),
	PAD_CFG_NATIVE(GPP_A10, NF1),
	PAD_CFG_IN_DRV(GPP_A11),
	PAD_CFG_GPI_SCI(GPP_A12, NONE, PLTRST, LEVEL, INVERT),
	PAD_CFG_NATIVE(GPP_A13, NF1),
	PAD_CFG_NATIVE(GPP_A15, NF1),
	PAD_CFG_OUTPUT(GPP_A16, 0),
	PAD_CFG_OUTPUT(GPP_A17, 0),
	PAD_CFG_IN_DRV(GPP_A18),
	/* GPP_A19 - RESERVED */
	PAD_CFG_IN_DRV(GPP_A20),
	PAD_CFG_IN_DRV(GPP_A21),
	PAD_CFG_IN_DRV(GPP_A22),
	PAD_CFG_IN_DRV(GPP_A23),

	/* ------- GPIO Group B ------- */
	PAD_CFG_OUTPUT(GPP_B0, 0), /* Toggle SMBus mux to disable access to DIMM SPDs */
	PAD_CFG_IN_DRV(GPP_B1),
	PAD_CFG_IN_DRV(GPP_B2),
	PAD_CFG_OUTPUT(GPP_B3, 0),
	PAD_CFG_OUTPUT(GPP_B4, 0),
	PAD_CFG_OUTPUT(GPP_B5, 0),
	PAD_CFG_IN_DRV(GPP_B6),
	PAD_CFG_OUTPUT(GPP_B7, 0),
	PAD_CFG_OUTPUT(GPP_B8, 0),
	PAD_CFG_OUTPUT(GPP_B9, 0),
	PAD_CFG_OUTPUT(GPP_B10, 0),
	PAD_CFG_OUTPUT(GPP_B11, 0),
	PAD_CFG_NATIVE(GPP_B14, NF1),
	PAD_CFG_OUTPUT(GPP_B15, 1),
	PAD_CFG_OUTPUT(GPP_B16, 1),
	PAD_CFG_OUTPUT(GPP_B17, 0),
	PAD_CFG_IN_DRV(GPP_B18),
	PAD_CFG_IN_DRV(GPP_B19),
	PAD_CFG_OUTPUT(GPP_B20, 1),
	PAD_CFG_OUTPUT(GPP_B21, 1),
	PAD_CFG_IN_DRV(GPP_B22),
	PAD_CFG_NATIVE(GPP_B23, NF2),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group C ------- */
	/* GPP_C0 - RESERVED */
	/* GPP_C1 - RESERVED */
	PAD_CFG_IN_DRV(GPP_C2),
	/* GPP_C3 - RESERVED */
	/* GPP_C4 - RESERVED */
	PAD_CFG_GPI_INT(GPP_C8, NONE, PLTRST, OFF),
	PAD_CFG_GPI_INT(GPP_C9, NONE, PLTRST, OFF),
	PAD_CFG_OUTPUT(GPP_C10, 1),
	PAD_CFG_OUTPUT(GPP_C11, 0),
	PAD_CFG_OUTPUT(GPP_C12, 0),
	PAD_CFG_OUTPUT(GPP_C13, 0),
	PAD_CFG_IN_DRV(GPP_C14),
	PAD_CFG_OUTPUT(GPP_C15, 0),
	PAD_CFG_NATIVE(GPP_C16, NF1),
	PAD_CFG_NATIVE(GPP_C17, NF1),
	PAD_CFG_NATIVE(GPP_C18, NF1),
	PAD_CFG_NATIVE(GPP_C19, NF1),
	/* GPP_C20 - RESERVED */
	PAD_CFG_OUTPUT(GPP_C21, 1),
	PAD_CFG_GPI_SMI(GPP_C22, NONE, PLTRST, EDGE_SINGLE, INVERT),
	PAD_CFG_IN_DRV(GPP_C23),

	/* ------- GPIO Group D ------- */
	PAD_CFG_GPI_NMI(GPP_D0, NONE, PLTRST, EDGE_SINGLE, INVERT),
	PAD_CFG_GPO(GPP_D1, 1, PLTRST),
	PAD_CFG_IN_DRV(GPP_D2),
	PAD_CFG_IN_DRV(GPP_D3),
	PAD_CFG_IN_DRV(GPP_D4),
	PAD_CFG_OUTPUT(GPP_D5, 0),
	PAD_CFG_OUTPUT(GPP_D6, 0),
	PAD_CFG_OUTPUT(GPP_D7, 0),
	PAD_CFG_OUTPUT(GPP_D8, 0),
	PAD_CFG_OUTPUT(GPP_D9, 0),
	PAD_CFG_OUTPUT(GPP_D10, 0),
	PAD_CFG_OUTPUT(GPP_D11, 0),
	PAD_CFG_OUTPUT(GPP_D12, 0),
	PAD_CFG_OUTPUT(GPP_D13, 0),
	PAD_CFG_OUTPUT(GPP_D14, 0),
	PAD_CFG_OUTPUT(GPP_D15, 0),
	PAD_CFG_OUTPUT(GPP_D16, 0),
	PAD_CFG_OUTPUT(GPP_D17, 0),
	PAD_CFG_OUTPUT(GPP_D18, 0),
	PAD_CFG_OUTPUT(GPP_D19, 0),
	PAD_CFG_OUTPUT(GPP_D20, 0),
	PAD_CFG_OUTPUT(GPP_D21, 0),
	PAD_CFG_OUTPUT(GPP_D22, 0),
	PAD_CFG_OUTPUT(GPP_D23, 0),

	/* ------- GPIO Group G ------- */
	PAD_CFG_OUTPUT(GPP_G0, 0),
	PAD_CFG_OUTPUT(GPP_G1, 0),
	PAD_CFG_OUTPUT(GPP_G2, 0),
	PAD_CFG_OUTPUT(GPP_G3, 0),
	PAD_CFG_OUTPUT(GPP_G4, 0),
	PAD_CFG_OUTPUT(GPP_G5, 0),
	PAD_CFG_OUTPUT(GPP_G6, 0),
	PAD_CFG_OUTPUT(GPP_G7, 0),

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPD ------- */
	PAD_CFG_OUTPUT(GPD0, 0),
	PAD_CFG_NATIVE(GPD1, NF1),
	PAD_CFG_NATIVE(GPD2, NF1),
	PAD_CFG_NATIVE(GPD3, NF1),
	PAD_CFG_NATIVE(GPD4, NF1),
	PAD_CFG_NATIVE(GPD5, NF1),
	PAD_CFG_NATIVE(GPD6, NF1),
	PAD_CFG_IN_DRV(GPD7),
	PAD_CFG_NATIVE(GPD8, NF1),
	PAD_CFG_OUTPUT(GPD9, 0),
	PAD_CFG_NATIVE(GPD10, NF1),
	PAD_CFG_OUTPUT(GPD11, 0),

	/* ------- GPIO Community 3 ------- */

	/* ------- GPIO Group K ------- */
	PAD_CFG_IN_DRV(GPP_K0),
	PAD_CFG_IN_DRV(GPP_K1),
	PAD_CFG_IN_DRV(GPP_K2),
	PAD_CFG_IN_DRV(GPP_K3),
	PAD_CFG_OUTPUT(GPP_K4, 0),
	PAD_CFG_OUTPUT(GPP_K5, 0),
	PAD_CFG_OUTPUT(GPP_K6, 0),
	PAD_CFG_OUTPUT(GPP_K7, 0),
	PAD_CFG_IN_DRV(GPP_K8),
	PAD_CFG_OUTPUT(GPP_K9, 0),
	PAD_CFG_OUTPUT(GPP_K10, 0),
	PAD_CFG_OUTPUT(GPP_K11, 0),
	PAD_CFG_IN_DRV(GPP_K12),
	PAD_CFG_IN_DRV(GPP_K13),
	PAD_CFG_IN_DRV(GPP_K14),
	PAD_CFG_OUTPUT(GPP_K15, 0),
	PAD_CFG_OUTPUT(GPP_K16, 0),
	PAD_CFG_IN_DRV(GPP_K17),
	PAD_CFG_OUTPUT(GPP_K18, 1),
	PAD_CFG_NATIVE(GPP_K19, NF1),
	PAD_CFG_OUTPUT(GPP_K20, 0),
	PAD_CFG_OUTPUT(GPP_K21, 0),
	PAD_CFG_IN_DRV(GPP_K22),
	PAD_CFG_IN_DRV(GPP_K23),

	/* ------- GPIO Group H ------- */
	PAD_CFG_OUTPUT(GPP_H0, 0),
	PAD_CFG_OUTPUT(GPP_H1, 0),
	PAD_CFG_IN_DRV(GPP_H2),
	PAD_CFG_OUTPUT(GPP_H3, 0),
	PAD_CFG_OUTPUT(GPP_H4, 0),
	/* GPP_H5 - RESERVED */
	PAD_CFG_OUTPUT(GPP_H6, 0),
	PAD_CFG_OUTPUT(GPP_H7, 0),
	PAD_CFG_OUTPUT(GPP_H8, 0),
	PAD_CFG_OUTPUT(GPP_H9, 0),
	/* GPP_H10 - RESERVED */
	/* GPP_H11 - RESERVED */
	PAD_CFG_GPO(GPP_H12, 1, PLTRST),
	/* GPP_H13 - RESERVED */
	/* GPP_H14 - RESERVED */
	PAD_CFG_GPI_INT(GPP_H15, NONE, PLTRST, OFF),
	/* GPP_H16 - RESERVED */
	/* GPP_H17 - RESERVED */
	PAD_CFG_IN_DRV(GPP_H18),
	PAD_CFG_GPO(GPP_H19, 1, PLTRST),
	PAD_CFG_GPO(GPP_H20, 1, PLTRST),
	PAD_CFG_GPO(GPP_H21, 0, PLTRST),
	PAD_CFG_GPO(GPP_H22, 0, PLTRST),
	PAD_CFG_OUTPUT(GPP_H23, 0),

	/* ------- GPIO Group E ------- */
	PAD_CFG_OUTPUT(GPP_E0, 0),
	PAD_CFG_IN_DRV(GPP_E2),
	PAD_CFG_IN_DRV(GPP_E3),
	PAD_CFG_OUTPUT(GPP_E4, 0),
	PAD_CFG_IN_DRV(GPP_E5),
	PAD_CFG_GPI_NMI(GPP_E6, NONE, PLTRST, EDGE_SINGLE, INVERT),
	PAD_CFG_OUTPUT(GPP_E7, 0),
	PAD_CFG_NATIVE(GPP_E8, NF1),

	/* ------- GPIO Group F ------- */
	PAD_CFG_IN_DRV(GPP_F0),
	PAD_CFG_IN_DRV(GPP_F1),
	PAD_CFG_IN_DRV(GPP_F2),
	PAD_CFG_IN_DRV(GPP_F3),
	PAD_CFG_IN_DRV(GPP_F4),
	PAD_CFG_IN_DRV(GPP_F5),
	PAD_CFG_IN_DRV(GPP_F6),
	PAD_CFG_IN_DRV(GPP_F7),
	PAD_CFG_IN_DRV(GPP_F8),
	PAD_CFG_IN_DRV(GPP_F9),
	PAD_CFG_NATIVE(GPP_F10, NF1),
	PAD_CFG_NATIVE(GPP_F11, NF1),
	PAD_CFG_NATIVE(GPP_F12, NF1),
	PAD_CFG_NATIVE(GPP_F13, NF1),
	PAD_CFG_OUTPUT(GPP_F14, 0),
	PAD_CFG_OUTPUT(GPP_F17, 0),
	PAD_CFG_OUTPUT(GPP_F18, 0),
	PAD_CFG_OUTPUT(GPP_F19, 0),
	PAD_CFG_OUTPUT(GPP_F20, 0),
	PAD_CFG_OUTPUT(GPP_F21, 0),
	PAD_CFG_OUTPUT(GPP_F22, 0),

	/* ------- GPIO Group J ------- */
	PAD_CFG_NATIVE(GPP_J2, NF1),
	PAD_CFG_NATIVE(GPP_J3, NF1),
	PAD_CFG_IN_DRV(GPP_J4),
	PAD_CFG_IN_DRV(GPP_J5),
	PAD_CFG_IN_DRV(GPP_J6),
	PAD_CFG_OUTPUT(GPP_J7, 1),
	PAD_CFG_OUTPUT(GPP_J8, 1),
	PAD_CFG_IN_DRV(GPP_J9),
	PAD_CFG_IN_DRV(GPP_J10),
	PAD_CFG_IN_DRV(GPP_J11),
};

/* Early pad configuration in romstage */
static const struct pad_config early_gpio_table[] = {
	PAD_CFG_OUTPUT(GPP_B0, 1), /* Toggle SMBus mux to read DIMM SPDs */
};

void program_early_gpio_pads(void)
{
	gpio_configure_pads(early_gpio_table, ARRAY_SIZE(early_gpio_table));
}

void program_gpio_pads(void *unused)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
