/* SPDX-License-Identifier: GPL-2.0-only */

#include <commonlib/helpers.h>
#include <soc/gpio.h>
#include <intelblocks/gpio_defs.h>

#include "../../gpio.h"

/* Less verbose GPIO macros, names have the same length on purpose */
#define PAD_CFG_IN_DRV(pad)		PAD_CFG_GPI_INT(pad, NONE, DEEP, OFF)
#define PAD_CFG_OUTPUT(pad, lvl)	PAD_CFG_GPO(pad, lvl, DEEP)
#define PAD_CFG_NATIVE(pad, fun)	PAD_CFG_NF(pad, NONE, DEEP, fun)

/* Pad configuration was generated automatically using intelp2m utility */
static const struct pad_config gpio_table[] = {

	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_A ------- */
	PAD_CFG_NF(GPP_A0, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A1, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A2, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A3, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A4, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A5, NONE, DEEP, NF3),
	PAD_CFG_GPO(GPP_A6, 0, DEEP),
	PAD_CFG_NF(GPP_A7, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A8, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_A9, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A10, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_A11, 0, DEEP),
	PAD_CFG_GPO(GPP_A12, 0, DEEP),
	PAD_CFG_NF(GPP_A13, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_A14, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_A15, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_A16, 0, DEEP),
	PAD_CFG_GPO(GPP_A17, 0, DEEP),
	PAD_CFG_GPO(GPP_A18, 0, DEEP),
	PAD_CFG_GPO(GPP_A19, 0, DEEP),
	PAD_CFG_GPO(GPP_A20, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_A21, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A22, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_A23, 0, DEEP),

	/* ------- GPIO Group GPP_B ------- */
	PAD_CFG_GPO(GPP_B0, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_B1, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_B2, 0, DEEP),
	PAD_CFG_GPO(GPP_B3, 0, DEEP),
	PAD_CFG_GPO(GPP_B4, 0, DEEP),
	PAD_CFG_GPO(GPP_B5, 0, DEEP),
	PAD_CFG_GPO(GPP_B6, 0, DEEP),
	PAD_CFG_GPO(GPP_B7, 0, DEEP),
	PAD_CFG_GPO(GPP_B8, 0, DEEP),
	PAD_CFG_GPO(GPP_B9, 0, DEEP),
	PAD_CFG_GPO(GPP_B10, 0, DEEP),
	PAD_CFG_GPO(GPP_B11, 0, DEEP),
	PAD_CFG_GPO(GPP_B12, 0, DEEP),
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_B15, 1, DEEP),
	PAD_CFG_GPO(GPP_B16, 1, DEEP),
	PAD_CFG_GPO(GPP_B17, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_B18, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B19, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_B20, 1, DEEP),
	PAD_CFG_GPO(GPP_B21, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_B22, NONE, DEEP, OFF, ACPI),
	PAD_CFG_NF(GPP_B23, NONE, DEEP, NF2),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_C ------- */
	/* GPP_C0 - RESERVED */
	/* GPP_C1 - RESERVED */
	PAD_CFG_NF(GPP_C2, NONE, DEEP, NF1),
	/* GPP_C3 - RESERVED */
	/* GPP_C4 - RESERVED */
	PAD_CFG_GPI_TRIG_OWN(GPP_C5, NONE, DEEP, OFF, ACPI),
	/* GPP_C6 - RESERVED */
	/* GPP_C7 - RESERVED */
	PAD_CFG_GPO(GPP_C8, 0, DEEP),
	PAD_CFG_GPO(GPP_C9, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_C10, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_C11, 0, DEEP),
	PAD_CFG_GPO(GPP_C12, 0, DEEP),
	PAD_CFG_GPO(GPP_C13, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_C14, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_C15, 0, DEEP),
	PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_C18, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_C19, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_C20, 1, DEEP),
	PAD_CFG_GPO(GPP_C21, 0, DEEP),
	PAD_CFG_GPI_SMI(GPP_C22, NONE, PLTRST, EDGE_SINGLE, INVERT),
	PAD_CFG_GPO(GPP_C23, 0, DEEP),

	/* ------- GPIO Group GPP_D ------- */
	PAD_CFG_GPI_NMI(GPP_D0, NONE, PLTRST, EDGE_SINGLE, INVERT),
	PAD_CFG_GPO(GPP_D1, 0, DEEP),
	PAD_CFG_GPO(GPP_D2, 0, DEEP),
	PAD_CFG_GPO(GPP_D3, 0, DEEP),
	PAD_CFG_GPO(GPP_D4, 0, DEEP),
	PAD_CFG_GPO(GPP_D5, 0, DEEP),
	PAD_CFG_GPO(GPP_D6, 0, DEEP),
	PAD_CFG_GPO(GPP_D7, 0, DEEP),
	PAD_CFG_GPO(GPP_D8, 0, DEEP),
	PAD_CFG_GPO(GPP_D9, 0, DEEP),
	PAD_CFG_GPO(GPP_D10, 0, DEEP),
	PAD_CFG_GPO(GPP_D11, 0, DEEP),
	PAD_CFG_GPO(GPP_D12, 0, DEEP),
	PAD_CFG_GPO(GPP_D13, 0, DEEP),
	PAD_CFG_GPO(GPP_D14, 0, DEEP),
	PAD_CFG_GPO(GPP_D15, 0, DEEP),
	PAD_CFG_GPO(GPP_D16, 0, DEEP),
	PAD_CFG_GPO(GPP_D17, 0, DEEP),
	PAD_CFG_GPO(GPP_D18, 0, DEEP),
	PAD_CFG_GPO(GPP_D19, 0, DEEP),
	PAD_CFG_GPO(GPP_D20, 0, DEEP),
	PAD_CFG_GPO(GPP_D21, 0, DEEP),
	PAD_CFG_GPO(GPP_D22, 0, DEEP),
	PAD_CFG_GPO(GPP_D23, 0, DEEP),

	/* ------- GPIO Group GPP_G ------- */
	PAD_CFG_GPO(GPP_G0, 0, DEEP),
	PAD_CFG_GPO(GPP_G1, 0, DEEP),
	PAD_CFG_GPO(GPP_G2, 0, DEEP),
	PAD_CFG_GPO(GPP_G3, 0, DEEP),
	PAD_CFG_GPO(GPP_G4, 0, DEEP),
	PAD_CFG_GPO(GPP_G5, 0, DEEP),
	PAD_CFG_GPO(GPP_G6, 0, DEEP),
	PAD_CFG_GPO(GPP_G7, 0, DEEP),

	/* ------- GPIO Group AZA ------- */

	/* ------- GPIO Group VGPIO_0 ------- */

	/* ------- GPIO Group VGPIO_1 ------- */

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPD ------- */
	PAD_CFG_NF(GPD0, NONE, DEEP, NF1),
	PAD_CFG_NF(GPD1, NONE, DEEP, NF1),
	PAD_CFG_NF(GPD2, NONE, DEEP, NF1),
	PAD_CFG_NF(GPD3, NONE, DEEP, NF1),
	PAD_CFG_NF(GPD4, NONE, DEEP, NF1),
	PAD_CFG_NF(GPD5, NONE, DEEP, NF1),
	PAD_CFG_NF(GPD6, NONE, DEEP, NF1),
	PAD_CFG_GPI_TRIG_OWN(GPD7, NONE, DEEP, OFF, ACPI),
	PAD_CFG_NF(GPD8, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPD9, 0, DEEP),
	PAD_CFG_NF(GPD10, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPD11, 0, DEEP),

	/* ------- GPIO Community 3 ------- */

	/* ------- GPIO Group GPP_K ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_K0, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_K1, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_K2, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_K3, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_K4, 0, DEEP),
	PAD_CFG_GPO(GPP_K5, 0, DEEP),
	PAD_CFG_GPO(GPP_K6, 0, DEEP),
	PAD_CFG_GPO(GPP_K7, 0, DEEP),
	PAD_CFG_GPO(GPP_K8, 0, DEEP),
	PAD_CFG_GPO(GPP_K9, 0, DEEP),
	PAD_CFG_GPO(GPP_K10, 0, DEEP),
	PAD_CFG_GPO(GPP_K11, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_K12, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_K13, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_K14, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_K15, 0, DEEP),
	PAD_CFG_GPO(GPP_K16, 0, DEEP),
	PAD_CFG_GPO(GPP_K17, 0, DEEP),
	PAD_CFG_GPO(GPP_K18, 0, DEEP),
	PAD_CFG_GPO(GPP_K19, 0, DEEP),
	PAD_CFG_GPO(GPP_K20, 0, DEEP),
	PAD_CFG_GPO(GPP_K21, 0, DEEP),
	PAD_CFG_GPO(GPP_K22, 0, DEEP),
	PAD_CFG_GPO(GPP_K23, 0, DEEP),

	/* ------- GPIO Group GPP_H ------- */
	PAD_CFG_GPO(GPP_H0, 0, DEEP),
	PAD_CFG_GPO(GPP_H1, 0, DEEP),
	PAD_CFG_GPO(GPP_H2, 0, DEEP),
	PAD_CFG_GPO(GPP_H3, 0, DEEP),
	PAD_CFG_GPO(GPP_H4, 0, DEEP),
	/* GPP_H5 - RESERVED */
	PAD_CFG_GPO(GPP_H6, 0, DEEP),
	PAD_CFG_GPO(GPP_H7, 0, DEEP),
	PAD_CFG_GPO(GPP_H8, 0, DEEP),
	PAD_CFG_GPO(GPP_H9, 0, DEEP),
	/* GPP_H10 - RESERVED */
	/* GPP_H11 - RESERVED */
	PAD_CFG_GPO(GPP_H12, 0, DEEP),
	/* GPP_H13 - RESERVED */
	/* GPP_H14 - RESERVED */
	PAD_CFG_GPI_TRIG_OWN(GPP_H15, NONE, DEEP, OFF, ACPI),
	/* GPP_H16 - RESERVED */
	/* GPP_H17 - RESERVED */
	PAD_CFG_GPO(GPP_H18, 0, DEEP),
	PAD_CFG_GPO(GPP_H19, 0, DEEP),
	PAD_CFG_GPO(GPP_H20, 0, DEEP),
	PAD_CFG_GPO(GPP_H21, 0, DEEP),
	PAD_CFG_GPO(GPP_H22, 0, DEEP),
	PAD_CFG_GPO(GPP_H23, 0, DEEP),

	/* ------- GPIO Group GPP_E ------- */
	PAD_CFG_GPO(GPP_E0, 0, DEEP),
	PAD_CFG_GPO(GPP_E1, 0, DEEP),
	PAD_CFG_GPO(GPP_E2, 0, DEEP),
	/* GPP_E3 - RESERVED */
	PAD_CFG_GPO(GPP_E4, 0, DEEP),
	PAD_CFG_GPO(GPP_E5, 0, DEEP),
	PAD_CFG_GPI_NMI(GPP_E6, NONE, PLTRST, EDGE_SINGLE, INVERT),
	PAD_CFG_GPO(GPP_E7, 0, DEEP),
	PAD_CFG_NF(GPP_E8, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_E9, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_E10, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_E11, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_E12, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_F ------- */
	PAD_CFG_GPO(GPP_F0, 0, DEEP),
	PAD_CFG_GPO(GPP_F1, 0, DEEP),
	PAD_CFG_GPO(GPP_F2, 0, DEEP),
	PAD_CFG_GPO(GPP_F3, 0, DEEP),
	PAD_CFG_GPO(GPP_F4, 0, DEEP),
	PAD_CFG_GPI_TRIG_OWN(GPP_F5, NONE, DEEP, OFF, ACPI),
	PAD_CFG_GPO(GPP_F6, 0, DEEP),
	PAD_CFG_GPO(GPP_F7, 0, DEEP),
	PAD_CFG_GPO(GPP_F8, 0, DEEP),
	PAD_CFG_GPO(GPP_F9, 0, DEEP),
	PAD_CFG_NF(GPP_F10, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F11, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F12, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F13, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_F14, 0, DEEP),
	PAD_CFG_NF(GPP_F15, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F16, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F17, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F18, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F19, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F20, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F21, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_F22, 0, DEEP),
	PAD_CFG_GPO(GPP_F23, 0, DEEP),

	/* ------- GPIO Group SPI ------- */

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group CPU ------- */

	/* ------- GPIO Group JTAG ------- */

	/* ------- GPIO Group GPP_I ------- */
	PAD_CFG_NF(GPP_I0, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I1, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I2, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_I3, 0, DEEP),
	PAD_CFG_NF(GPP_I4, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I5, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I6, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I7, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I8, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I9, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_I10, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_I11, 0, DEEP),
	PAD_CFG_GPO(GPP_I12, 0, DEEP),
	PAD_CFG_GPO(GPP_I13, 0, DEEP),
	PAD_CFG_GPO(GPP_I14, 0, DEEP),

	/* ------- GPIO Group GPP_J ------- */
	PAD_CFG_GPO(GPP_J0, 0, DEEP),
	PAD_CFG_NF(GPP_J1, NONE, DEEP, NF2),
	PAD_CFG_GPO(GPP_J2, 0, DEEP),
	PAD_CFG_GPO(GPP_J3, 0, DEEP),
	PAD_CFG_NF(GPP_J4, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_J5, 0, DEEP),
	PAD_CFG_NF(GPP_J6, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_J7, 0, DEEP),
	PAD_CFG_GPO(GPP_J8, 0, DEEP),
	PAD_CFG_NF(GPP_J9, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_J10, 0, DEEP),
	PAD_CFG_GPO(GPP_J11, 0, DEEP),
};

/* Early pad configuration in romstage */
static const struct pad_config early_gpio_table[] = {
	PAD_CFG_OUTPUT(GPP_B0, 1), /* Toggle SMBus mux to read DIMM SPDs */
};

void program_early_gpio_pads(void)
{
	gpio_configure_pads(early_gpio_table, ARRAY_SIZE(early_gpio_table));
}

void program_gpio_pads(void *unused)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
